---
abstract: 'validate Russian pension fund number'
author:
  - 'Ivan Bessarabov <ivan@bessarabov.ru>'
build_requires:
  Test::More: 0
  feature: 0
  open: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-PFR
requires:
  Carp: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/bessarabov/Business-PFR/issues
  homepage: https://github.com/bessarabov/Business-PFR
  repository: https://github.com/bessarabov/Business-PFR.git
version: 1.0.0
